version: '3.8'

services:
  # Welcome (Vue.js) - 포트 3000
  welcome-vue:
    build:
      context: ./welcome-vue
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # My Codit (Vue.js) - 포트 8080
  my-codit-vue:
    build:
      context: .
      dockerfile: Dockerfile.vue
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VUE_APP_SUPABASE_URL=${VUE_APP_SUPABASE_URL}
      - VUE_APP_SUPABASE_ANON_KEY=${VUE_APP_SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - app-network

  # Portfolio (Vue.js) - 포트 3001
  portfolio-vue:
    build:
      context: ./portfolio-vue
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-multi.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # SSL 인증서 (선택사항)
    depends_on:
      - welcome-vue
      - my-codit-vue
      - portfolio-vue
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data: