version: '3.8'

services:
  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vue
      - nextjs
    networks:
      - app-network

  # Vue.js 관리자 앱
  vue:
    build:
      context: .
      dockerfile: Dockerfile.vue
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Next.js 포트폴리오 앱  
  nextjs:
    build:
      context: ./portfolio-nextjs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge